### ISSUE TITLE
Remove compiled modules from thr manifesto-3d repository

### ISSUE THREAD

**Issue by vincentmarchetti** [IIIF-Commons/manifesto-3d#10]
Now that publishing the compiled modules on npm registry (@iiif/3d-manifesto-dev ) has been done, we should remove the compiled products from the github repository. These would be the folders
dist-commonjs
dist-esmodule
dist-umd
dist-var
types

These were only included in the initial days of the manifesto-3d repository to allow npm to install from the github repository, no longer needed since we can install from npm registry.

This would reduce the byteage going back and forth on checkouts and commits, and also remove the confusion over whether the compiled products are in sync with the source code.

I propose we decide and potentially do this at the next ( Aug 1 ) IIIF-Commons call.

**Comment by glenrobson** [comment]
Done
