### ISSUE TITLE
Setup this repo to deploy to NPM

### ISSUE THREAD

**Issue by glenrobson** [IIIF-Commons/manifesto-3d#2]
Change the following:

https://github.com/IIIF-Commons/manifesto-3d/blob/master/.github/workflows/release.yml

To deploy to NPM but not to overwrite the existing latest version at:

https://www.npmjs.com/package/manifesto.js

@edsilv to invite @luguenth to the NPM iiif-commons repo.

**Comment by vincentmarchetti** [comment]
Lukas has renamed the package to manifesto3d in the package.json file (already committed) to support the deployment in npm without interfering with the existing manifesto.js npm package. I think with that change we can also change the version to a simpler npm semantic version. The version of the package is now "4.3.0-draft3dapi.0.5.0" ; the 4.3.0 refers to the latest manifesto.js version. I would propose setting the manifesto3d package.json version to 0.5.0; I leave it to Lukas to make that change if he agrees.

I will also recompile the modules with the new package name, commit them to a branch of iiif-commons/manifesto3d that I have created named kshell-dev. I will create a pull request to move those new compiled modules into master, and at that time we'll make sure we're all rowing in the same direction.

**Comment by luguenth** [comment]
Wasn't able to continue work here yesterday, so I try to set up a working NPM publishing pipeline today.
Regarding the versioning @vincentmarchetti, your proposal sounds good, and I'll reflect that in the package.json.

**Comment by luguenth** [comment]
I think everything should be in place now. The only thing I can't do is to set the NPM Token secret in the settings of the Repo. @glenrobson I think you can access the settings to set the secret. After setting them, a release with a new Tag should do the trick, I suppose.

**Comment by glenrobson** [comment]
Notes from todays meeting:

 * Setup new NPM repo under the @iiif organisation on npm. 
 * Will only use this deployment for the duration of development look to end around June 2025.
 * Glen to ask Stephen to access the IIIF organization on NPM.  Owner or admin. Invite all as members or as a Team

**Comment by vincentmarchetti** [comment]
Deployment to NPM was implemented at IIIF-Commons call on July 17 2024
The npm package name is @iiif/3d-manifesto-dev
